language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

branches:
  only:
    - master
    - /^\d+\.\d+$/

matrix:
  include:
    - php: 5.6
      env:
        - PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
        - COVERAGE=true
    - php: 5.6
      env: SYMFONY_VERSION='2.3.*'
    - php: 5.6
      env:
        - SYMFONY_VERSION='2.4.*'
        - FRAMEWORK_EXTRA_VERSION='~3.0'
    - php: 5.6
      env:
        - SYMFONY_VERSION='2.5.*'
        - FRAMEWORK_EXTRA_VERSION='~3.0'
    - php: 5.6
      env:
        - SYMFONY_VERSION='2.6.*'
        - FRAMEWORK_EXTRA_VERSION='~3.0'
    - php: 5.6
      env:
        - SYMFONY_VERSION='2.7.*'
        - FRAMEWORK_EXTRA_VERSION='~3.0'
    - php: 5.6
      env:
        - SYMFONY_VERSION='2.8.*@dev'
        - FRAMEWORK_EXTRA_VERSION='~3.0'
    - php: 5.4
      env:
        - SYMFONY_VERSION=2.3.*
        - COMPOSER_FLAGS="--prefer-lowest"

before_script:
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi;'
  - sh -c 'if [ "$FRAMEWORK_EXTRA_VERSION" != "" ]; then composer require --dev --no-update sensio/framework-extra-bundle=$FRAMEWORK_EXTRA_VERSION; fi;'
  - if [[ "$TRAVIS_PHP_VERSION" == "5.4" || "$TRAVIS_PHP_VERSION" == "hhvm" ]]; then composer remove "php-http/guzzle6-adapter" --dev --no-update; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "5.4" || "$TRAVIS_PHP_VERSION" == "hhvm" ]]; then composer require "php-http/guzzle5-adapter" --dev --no-update; fi
  - composer update $COMPOSER_FLAGS --no-interaction
  - sudo apt-get install python-sphinx enchant
  - sudo pip install -r Resources/doc/requirements.txt

script:
  - SYMFONY_DEPRECATIONS_HELPER=weak phpunit ${PHPUNIT_FLAGS}
  - make -C Resources/doc SPHINXOPTS='-nW' html
  - make -C Resources/doc spelling

after_script:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

after_failure:
  - cat /tmp/fos-http-cache-bundle/logs/test.log
